# analysis_options.yaml
include: package:flutter_lints/flutter.yaml

# เพิ่ม rules เหล่านี้
linter:
  rules:
    # แจ้งเตือน const
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    
    # rules อื่นๆ ที่มีประโยชน์
    always_declare_return_types: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_build_context_synchronously: true

analyzer:
  errors:
    use_build_context_synchronously: ignore
    avoid_print: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"