version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: art123
      MYSQL_DATABASE: flutter_db
      MYSQL_USER: art123
      MYSQL_PASSWORD: art123
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-data: